services:
  app:
    build: .
    configs:
      - source: dock.yaml
        target: /config.yaml
    ports:
      - 9001:9001
      - 9002:9002
      - 9003:9003

configs:
  dock.yaml:
    content: |
      rfinger:
        default: http://localhost:9003
        pictures:
          turetek:
            regular: https://thskth.se/wp-content/uploads/2023/06/ths-logo-bla-01-300x294-1.png
            small: https://thskth.se/wp-content/uploads/2019/12/ths-logo-svart-01.png
          diadat:
            regular: https://dsekt-assets.s3.amazonaws.com/logotyp
            small: https://dsekt-assets.s3.amazonaws.com/logotyp
          marmed:
            regular: https://storage.googleapis.com/medieteknik-static/static/logos/logo.webp
            small: https://storage.googleapis.com/medieteknik-static/static/logos/logo.webp
          karklu:
            regular: https://dsekt-assets.s3.amazonaws.com/website/namnder/dkm.svg
            small: https://dsekt-assets.s3.amazonaws.com/website/namnder/dkm.svg
      ston:
        nollan:
          - id: 0
            name: Ture Teknolog
            street: Jerkas väg 1
            zip: 134 32
            city: Gustavsberg
          - id: 1
            name: Diana Datalog
            street: Osquars backe 21
            zip: 114 28
            city: Stockholm
          - id: 2
            name: Martin Median
            street: Drottning Kristinas väg 15
            zip: 114 28
            city: Stockholm
      spam:
